/// Flutter icons SearchIconExternal
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SearchIconExternal
///      fonts:
///       - asset: fonts/SearchIconExternal.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SearchIconExternal {
  SearchIconExternal._();

  static const _kFontFam = 'SearchIconExternal';
  static const String? _kFontPkg = null;

  static const IconData search_1 = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
